dist: xenial
os: linux
language: minimal
services: docker
jobs:
  include:
    # OK case
    - env:
        - BASE_IMAGE=fedora:rawhide
    # OK case
    - env:
        - BASE_IMAGE=fedora:31
    # OK case
    - env:
        - BASE_IMAGE=centos:8.1.1911
    # NG case: Macro is not evaluated.
    - env:
        - BASE_IMAGE=centos:7.7.1908
    # OK case: Macro is evaluated.
    - env:
        - BASE_IMAGE=centos:7.7.1908
      before_install:
        - sed -i '/bcond_without git/ s/%/%%/' foo.spec
        - sed -i '/bcond_without git/ s/^/#/' foo.spec
        - grep bcond_without foo.spec
install:
  - |
    travis_retry docker build --rm -t my-container \
      --build-arg BASE_IMAGE=${BASE_IMAGE} \
      -f Dockerfile \
      .
script:
  - docker run --rm -t my-container
